### PR TITLE
Add support for Pop'n music Omnimix v2

### PR DESCRIPTION
**Pull request by xinrin**

### CODE REVIEW

**Comment by DragonMinded** [comment]
Thanks for the commit! I haven't looked at Pop'n omnimix, so I assume that it has XML files that it comes with for the songs that should be applied to it? Hence the loading of song info from XML. Also, this shouldn't load the data directly into the base game, Pop'n Music should be updated to support omnimix like IIDX and Museca have (omni flag, importing omnimix data into omni-22 instead of regular, etc).

**Comment by xinrin** [comment]
yeah works like that, but popnhax send a flag and its like this M39:J:A:X:datecode

**Comment by xinrin** [comment]
omni flag added

**Comment by DragonMinded** [comment]
Merged in #73.

**Pull request closed without merging**
