### PR TITLE
[sdvx]6代新组段位+段位称号组BUG修正

### PR DESCRIPTION
**Pull request by SimoTsuKi**
[bemani.zip](https://github.com/DragonMinded/bemaniutils/files/9843589/bemani.zip)

### CODE REVIEW

**Comment by Subject38** [comment]
uhhhhhhhhhhhhhhhhhhh LOL?

**Comment by wz18207** [comment]
LFMAO.

**Comment by Subject38** [comment]
actual review: this is completely unmergeable, nearly no one is really able or willing to switch to postgres for this project since it requires a massive migration that is not in the pull request as well as the fact that sysops would then need to change their setup entirely. this fact alone makes the pull request a complete nonstarter. the sdvx 6 code looks mostly fine i think at a glance but this pull request will be merged when hell freezes over

**Comment by jorpz** [comment]
This is one of the best PR emails I've had show up in my inbox.

**Comment by DragonMinded** [comment]
Hey! Thanks for the PR. However, as alluded by several other commenters, this isn't mergeable as-is. Also, it provides a direct competition with Konami for their current offerings. We do not wish to compete with them and respect their business efforts. We are trying to provide tools for historical examination and preservation of game experiences that are not available anymore and do not compete with Konami or the arcades that run their games.

**Pull request closed without merging**
